name: Spelling and Typos Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-spelling-and-typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run Speling and typos check
        run: |
          python workflow_scripts/spelling_and_typos_check.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Spelling and Typos Check
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Spelling and Typos Check
          body: |
            This PR was created by [Spelling and Typos Check]
          branch: spelling-and-typos-check
          base: main
          branch-suffix: timestamp
          delete-branch: true
          reviewers: INtina47
          labels: spelling-and-typos-check
          draft: false
          add-paths: -A
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib




